name: Justin Boone Reality
favicon: null
layout_spectrum: 1
typography_spectrum: 0.09326
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3a0d58'
    - '#c1b1cd'
    - '#e1d9e6'
    - '#7d5c92'
  brandStrength: 0.625
  lightness: 0.5820686409715563
  saturation: 0.02583410288207233
  rhythmicContrast: 0.21108455024659634
purpose: []
