name: Justin Boone Reality
favicon: null
layout_spectrum: 0.9298376757651567
typography_spectrum: 0.8144752699881792
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.040029308991506696
  lightness: 0.5820686409715563
  saturation: 0.02583410288207233
  rhythmicContrast: 0.21108455024659634
purpose: []
